### ISSUE TITLE
Cannot Equip Wand Foci

### ISSUE THREAD

**Issue by Vendy13** [TeamAmeriFrance/Electro-Magic-Tools#39]
I can't equip any of the wand foci provided by your mod. I have managed to craft them, however they don't show up when I press 'F' and I can't even put them in my focus pouch. I am able to equip the vanilla foci as well as foci from other mods. I believe I am using the most recent versions of this (2.0.0 Alpha 28) as well as of Thaumcraft (4.2.3.3). I'm really looking forward to being able to summon snowmen, so any help or advice is appreciated! :)

**Comment by fewizz** [comment]
https://www.dropbox.com/s/k7jbtyxdcp75ruq/ElectroMagicTools-1.7.10-2.0.0Alpha-CUSTOM.jar?dl=0

**Comment by fewizz** [comment]
in this version foci "equipable"

**Comment by Tombenpotter** [comment]
I will not support any issue with this version.

**Comment by Vendy13** [comment]
Okay. Is there any reason you know that it wouldn't work for the official version, Tom?

**Comment by fewizz** [comment]
Outdated thaumcraft api compatibility.

**Comment by Vendy13** [comment]
Ah, I see. I'll just use the custom version for now then. Thanks!

**Comment by Tombenpotter** [comment]
As a matter of fact I do. The last version out was released before Thaumcraft changed its focus system. Once EMT 2.0 is released, it'll be fixed. For now, I'm sorry :p

**Comment by Vendy13** [comment]
It's fine. Great to know it's being fixed! :)

**Comment by fewizz** [comment]
Tombenpotter, good luck.
