### ISSUE TITLE
Chest Loot Bug

### ISSUE THREAD

**Issue by Dream-Master** [TeamAmeriFrance/Electro-Magic-Tools#41]
Find this Item in Chets. ?

https://www.dropbox.com/s/pe2bnrm39uckvyw/Screenshot%202015-06-27%2020.24.38.png?dl=0

@fewizz I using your V4 Version

**Comment by TehNut** [comment]
Either use the unofficial version or drop EMT. The mod is dead currently.

**Comment by Dream-Master** [comment]
@TehNut  Ok thanks

@fewizz 
Can you help with this issue?
